server:
    port: 8083

spring:
    datasource:
                url: jdbc:h2:mem:librarydb
                driverClassName: org.h2.Driver
                username: sa
                password: password

    h2:
        console:
              enabled: true

